### ISSUE TITLE
java.io.IOException: Permission denied at java.io.File.createTempFile

### ISSUE THREAD

**Issue by fabianignacio** [mgks/Android-SmartWebView#12]
Hi! Congrats on your work!
I have one problem using the capture feature, to open the native camera. After giving the permission for using the camera, I get always java.io.IOException: Permission denied, so the only intent launched in the capture input is the file chooser.
What I'm ding wrong?

Here is a stacktrce:

```
                                                                             java.io.IOException: Permission denied
                                                                                 at java.io.UnixFileSystem.createFileExclusively0(Native Method)
                                                                                 at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
                                                                                 at java.io.File.createNewFile(File.java:948)
                                                                                 at java.io.File.createTempFile(File.java:1862)
```

Thanks

Fabian

**Comment by mgks** [comment]
have you checked custom variables carefully?

**Comment by mgks** [comment]
As you've not provided any update by now and this issues seems to have occurred because of custom variable configuration or app permissions not being set right, I've to close this.
You can still open this issues if unresolved.
