### ISSUE TITLE
What if phone doesn't have external SD card?

### ISSUE THREAD

**Issue by sandeepthaliyil** [mgks/Android-SmartWebView#16]
I am getting the error
```
Image file creation failed
java.io.IOException: open failed: ENOENT (No such file or directory)
at java.io.File.createNewFile(File.java:939)
at java.io.File.createTempFile(File.java:1004)
at MainActivity.create_image(MainActivity.java:507)
```
on line 507 the code is
```
File sd_directory   = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_PICTURES);
return File.createTempFile(new_name, ".jpg", sd_directory);
```
My phone doesn't have external storage card.

**Comment by sandeepthaliyil** [comment]
On another phone i am getting the error
```
Image file creation failed
java.io.IOException: Permission denied
at java.io.UnixFileSystem.createFileExclusively0(Native Method)
at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
at java.io.File.createNewFile(File.java:948)
at java.io.File.createTempFile(File.java:1862)
at in.lulumall.loyalty.MainActivity.create_image(MainActivity.java:507)
at in.lulumall.loyalty.MainActivity.access$400(MainActivity.java:58)
at in.lulumall.loyalty.MainActivity$2.onShowFileChooser(MainActivity.java:226)
```

**Comment by mgks** [comment]
you haven't provided proper permissions to the app.

**Comment by sandeepthaliyil** [comment]
```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.WAKE_LOCK" />
<uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
<uses-permission android:name="android.permission.CALL_PHONE" />
<uses-permission android:name="android.permission.CAMERA"/>
<uses-feature android:name="android.hardware.camera.autofocus" />
<uses-feature android:name="android.hardware.camera" android:required="true" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />
<uses-feature android:name="android.hardware.touchscreen" android:required="false" />
```
These are the permissions i gave. But this error is not in all models few models above Android 6

**Comment by mgks** [comment]
Can I get details of both devices? including SDK, RAM, ROM and also Manufacturer if not using virtual device.
