### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by ismalel** [mgks/Android-SmartWebView#173]
Hi,

The app works great but im having issues downloading files

Error:
` Process: mgks.os.webview, PID: 10751
    java.lang.IllegalArgumentException: Can only download HTTP/HTTPS URIs: blob:https://webapp.com/7dc5df5b-bb63-4852-98a1-1df89b34712e
        at android.app.DownloadManager$Request.<init>(DownloadManager.java:497)
        at mgks.os.webview.MainActivity$5.onDownloadStart(MainActivity.java:361)
        at Ox0.handleMessage(chromium-Monochrome.aab-stable-410410673:157)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6864)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)`

Im doing something wrong?

**Comment by mgks** [comment]
Seems like app is trying to download a blog file.
Download function is configured to process complete file URIs only, that's why it could be happening.

**Comment by indraAsLesmana** [comment]
same issue, my problem The website give me base64 image **data:image/png;base64** not static URL.

**Comment by mgks** [comment]
is this happening in any specific device or android version?

**Comment by indraAsLesmana** [comment]
all new android version i think starting 6. require file path provider write on xml. if it not setup it will crash.
