### ISSUE TITLE
TransactionTooLargeException issue

### ISSUE THREAD

**Issue by perochak** [mgks/Android-SmartWebView#254]
Hey

Facing issue when taking photos using camera for multiple instances.
```
RuntimeException: android.os.TransactionTooLargeException: data parcel size 639572 bytes
    at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:201)
    at android.app.ActivityThread.main(ActivityThread.java:6861)
```
Any help?

**Comment by perochak** [comment]
This worked for me
`    protected void onSaveInstanceState(Bundle outState ){
		int osVersion = android.os.Build.VERSION.SDK_INT;
		if ( osVersion < Build.VERSION_CODES.N) {
			super.onSaveInstanceState(outState);
			asw_view.saveState(outState);
		}


    }`
