### ISSUE TITLE
camera only input field app crash 

### ISSUE THREAD

**Issue by frogsuite** [mgks/Android-SmartWebView#295]
**Describe the bug**
app crash after  camera only input field selected and image is captured.

**Comment by mgks** [comment]
any error log?

**Comment by frogsuite** [comment]
the android device is  redmin not 5 pro with 
miui 12 

android version  :  9 PKQ1.180904.001


--------- beginning of system
--------- beginning of crash
--------- beginning of main
2023-10-13 15:12:28.509 19027-19027 CAM_CameraIntentManager pid-19027                            E  checkCallerLegality: Unknown caller: sample.faceapp.com
2023-10-13 15:12:28.539 19027-19027 CAM_CameraIntentManager pid-19027                            E  checkCallerLegality: Unknown caller: sample.faceapp.com
2023-10-13 15:12:28.604 19027-19027 CAM_CameraIntentManager pid-19027                            E  checkCallerLegality: Unknown caller: sample.faceapp.com
2023-10-13 15:12:29.922 19027-19027 CAM_CameraIntentManager pid-19027                            E  checkCallerLegality: Unknown caller: sample.faceapp.com
2023-10-13 15:12:29.926 19027-19027 CAM_CameraIntentManager pid-19027                            E  checkCallerLegality: Unknown caller: sample.faceapp.com
2023-10-13 15:12:30.359 19027-19027 CAM_CameraIntentManager pid-19027                            E  checkCallerLegality: Unknown caller: sample.faceapp.com
2023-10-13 15:12:37.656  2084-4070  ActivityTrigger         pid-2084                             E  activityResumeTrigger: not whiteListedsample.faceapp.com/mgks.os.swv.MainActivity/15
2023-10-13 15:12:37.754 18598-18598 AndroidRuntime          pid-18598                            E  FATAL EXCEPTION: main
                                                                                                    Process: sample.faceapp.com, PID: 18598
                                                                                                    java.lang.AssertionError
                                                                                                    	at mgks.os.swv.MainActivity.lambda$onCreate$0$mgks-os-swv-MainActivity(MainActivity.java:131)
                                                                                                    	at mgks.os.swv.MainActivity$$ExternalSyntheticLambda0.onActivityResult(Unknown Source:4)
                                                                                                    	at androidx.activity.result.ActivityResultRegistry$1.onStateChanged(ActivityResultRegistry.java:149)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:360)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:271)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:313)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:151)
                                                                                                    	at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
                                                                                                    	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
                                                                                                    	at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
                                                                                                    	at androidx.lifecycle.ReportFragment.onStart(ReportFragment.java:109)
                                                                                                    	at android.app.Fragment.performStart(Fragment.java:2548)
                                                                                                    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1334)
                                                                                                    	at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
                                                                                                    	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
                                                                                                    	at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3008)
                                                                                                    	at android.app.FragmentController.dispatchStart(FragmentController.java:193)
                                                                                                    	at android.app.Activity.performStart(Activity.java:7264)
                                                                                                    	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:2970)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:201)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6810)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
2023-10-13 15:12:37.924  2084-2162  InputDispatcher         pid-2084                             E  channel 'f51bb02 sample.faceapp.com/mgks.os.swv.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
c

**Comment by frogsuite** [comment]
any update with this ?

**Comment by mgks** [comment]
Fixed with #318
