### ISSUE TITLE
Crashing on App Start

### ISSUE THREAD

**Issue by Brattee** [mgks/Android-SmartWebView#82]
**Crashing on App Start**
Every time i start the App it crashes, this never happened to me before. Can the reason be that i update Android Studio?

**Crash Log - Building and Installing the App**

    2019-03-24 01:03:44.595 12795-12810/? E/MemoryLeakMonitorManager:             MemoryLeakMonitor.jar is not exist!
    2019-03-24 01:03:44.595 12795-12795/? E/Minikin: Could not get cmap table size!
    2019-03-24 01:03:44.714 12795-12819/? E/vndksupport: Could not load     vendor/lib64/egl/libGLES_mali_v2.so from sphal namespace: dlopen failed: library "vendor/lib64/egl/libGLES_mali_v2.so" not found.

**Crash Log - Starting the App**

    --------- beginning of crash
    2019-03-24 01:03:50.093 12795-12795/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mgks.os.webview, PID: 12795
    java.lang.RuntimeException: Unable to start activity ComponentInfo{mgks.os.webview/mgks.os.webview.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver android.webkit.WebView.getViewTreeObserver()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3297)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.ViewTreeObserver android.webkit.WebView.getViewTreeObserver()' on a null object reference
        at mgks.os.webview.MainActivity.onCreate(MainActivity.java:184)
        at android.app.Activity.performCreate(Activity.java:7383)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1218)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3250)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3405) 
        at android.app.ActivityThread.-wrap12(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1994) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
    2019-03-24 01:03:50.125 12795-12795/? I/Process: Sending signal. PID: 12795 SIG: 9

**Comment by mgks** [comment]
I apologize for not testing the last update. Thank you @Brattee for reporting and also @hongwen000 for noticing the mistake.
You can pull the latest update, it should work fine.
